import { Profile, Category, Expense } from '@/types';

export const MOCK_USERS: Profile[] = [
  {
    id: 'usr-husband-01',
    email: 'rahul@homeaudit.app',
    display_name: 'Rahul',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'usr-wife-02',
    email: 'wife@homeaudit.app',
    display_name: 'Apeksha',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  { id: 'cat-01', name: 'Groceries & Supplies', icon: 'ShoppingCart', color: '#10b981' },
  { id: 'cat-02', name: 'Utilities & Bills', icon: 'Zap', color: '#f59e0b' },
  { id: 'cat-03', name: 'Housing & Rent', icon: 'Home', color: '#3b82f6' },
  { id: 'cat-04', name: 'Dining Out & Food', icon: 'Utensils', color: '#ef4444' },
  { id: 'cat-05', name: 'Shopping & Apparel', icon: 'ShoppingBag', color: '#ec4899' },
  { id: 'cat-06', name: 'Health & Medical', icon: 'HeartPulse', color: '#8b5cf6' },
  { id: 'cat-07', name: 'Travel & Commute', icon: 'Car', color: '#06b6d4' },
  { id: 'cat-08', name: 'Entertainment', icon: 'Film', color: '#6366f1' },
  { id: 'cat-09', name: 'Personal Expenses', icon: 'User', color: '#14b8a6' },
  { id: 'cat-10', name: 'Miscellaneous', icon: 'MoreHorizontal', color: '#64748b' },
];

export const MOCK_EXPENSES: Expense[] = [
  {
    id: 'exp-101',
    user_id: 'usr-husband-01',
    category_id: 'cat-01',
    amount: 3450,
    title: 'Weekly Supermarket Groceries',
    description: 'Vegetables, fruits, milk, household cleaning items',
    expense_date: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    split_type: 'SHARED_50_50',
    user: MOCK_USERS[0],
    category: MOCK_CATEGORIES[0],
  },
  {
    id: 'exp-102',
    user_id: 'usr-wife-02',
    category_id: 'cat-02',
    amount: 2800,
    title: 'Electricity Bill - August',
    description: 'BESCOM electricity bill payment',
    expense_date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    split_type: 'SHARED_50_50',
    user: MOCK_USERS[1],
    category: MOCK_CATEGORIES[1],
  },
  {
    id: 'exp-103',
    user_id: 'usr-husband-01',
    category_id: 'cat-04',
    amount: 1420,
    title: 'Weekend Dinner Outing',
    description: 'Italian dinner at Cafe Pasta',
    expense_date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    split_type: 'SHARED_50_50',
    user: MOCK_USERS[0],
    category: MOCK_CATEGORIES[3],
  },
  {
    id: 'exp-104',
    user_id: 'usr-wife-02',
    category_id: 'cat-05',
    amount: 4500,
    title: 'Formal Shoes & Accessories',
    description: 'Personal shopping',
    expense_date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    split_type: 'INDIVIDUAL_PAID_BY_ME',
    user: MOCK_USERS[1],
    category: MOCK_CATEGORIES[4],
  },
  {
    id: 'exp-105',
    user_id: 'usr-husband-01',
    category_id: 'cat-07',
    amount: 1850,
    title: 'Car Fuel Refill',
    description: 'Full tank Petrol',
    expense_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    split_type: 'SHARED_50_50',
    user: MOCK_USERS[0],
    category: MOCK_CATEGORIES[6],
  },
  {
    id: 'exp-106',
    user_id: 'usr-wife-02',
    category_id: 'cat-08',
    amount: 999,
    title: 'Netflix & Spotify Annual Renewal',
    description: 'Household entertainment subscriptions',
    expense_date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    split_type: 'SHARED_50_50',
    user: MOCK_USERS[1],
    category: MOCK_CATEGORIES[7],
  },
  {
    id: 'exp-107',
    user_id: 'usr-husband-01',
    category_id: 'cat-03',
    amount: 32000,
    title: 'Monthly Apartment Maintenance & Rent',
    description: 'Shared house rent',
    expense_date: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
    split_type: 'SHARED_50_50',
    user: MOCK_USERS[0],
    category: MOCK_CATEGORIES[2],
  },
];
